name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE: "ghcr.io/${{ github.repository_owner }}/bgm38-tv"

    concurrency:
      group: ${{ github.workflow }}-${{ github.sha }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - run: echo "SHA=$(git show --no-patch --no-notes --date=short-local --pretty='%as-%h')" >> $GITHUB_ENV
        env:
          TZ: UTC

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=ref,event=branch,suffix=-${{ env.SHA }}

            type=raw,value=${{ env.SHA }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build Final Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          builder: ${{ steps.buildx.output.name }}
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
